name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.20.0"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Try Next.js build
        run: yarn build

      - name: Verify component structure
        run: |
          # Check core files
          test -f components/App.jsx || exit 1
          test -f pages/index.jsx || exit 1
          test -f pages/_app.jsx || exit 1
          echo "✅ Core files exist"

          # Check all main components
          test -f components/Core/index.js || exit 1
          test -f components/Ranked/Ranked.jsx || exit 1
          test -f components/Matchs/Matchs.jsx || exit 1
          test -f components/Champions/Champions.jsx || exit 1
          test -f components/Masteries/Masteries.jsx || exit 1
          echo "✅ All main components exist"

          # Check main hooks
          test -f hooks/usePlayerData.js || exit 1
          test -f hooks/data/useRankedData.js || exit 1
          test -f hooks/data/useMatchData.js || exit 1
          test -f hooks/data/useMasteriesData.js || exit 1
          test -f hooks/data/useChampionData.js || exit 1
          echo "✅ All data hooks exist"

          # Check contexts and utilities
          test -f contexts/ChampionContext.js || exit 1
          test -f utils/errorHandling.js || exit 1
          test -f utils/dateFormatter.js || exit 1
          test -f constants/queueTypes.js || exit 1
          echo "✅ All contexts and utilities exist"

      - name: Validate Next.js Tailwind configuration
        run: |
          test -f next.config.js || exit 1
          test -f tailwind.config.js || exit 1
          test -f postcss.config.js || exit 1
          echo "✅ Configuration files valid"

      - name: Check for common errors
        run: |
          # Check for forgotten console.log statements
          console_logs=$(find components/ pages/ -name "*.jsx" -o -name "*.js" | xargs grep -l "console\.log" | wc -l)
          if [ "$console_logs" -gt 0 ]; then
            echo "⚠️  Found $console_logs files with console.log statements"
          fi

          echo "✅ Basic validation completed"

      - name: Verify development server can start
        run: |
          # Test that the dev server starts (quick shutdown)
          timeout 15s yarn dev || [ $? -eq 124 ] && echo "✅ Dev server starts successfully"
